/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{html,js}"],
  theme: {
    extend: {},
  },
  safelist: [
    // Card component classes
    "bg-white",
    "shadow-md",
    "rounded-lg",
    "overflow-hidden",
    "max-w-sm",
    "mx-auto",
    "p-2",
    "min-w-[230px]",
    "max-w-[230px]",
    "w-full",
    "h-48",
    "object-cover",
    "text-xl",
    "font-bold",
    "mb-2",
    "text-gray-600",
    "flex",
    "gap-2",
    "mt-4",
    "bg-indigo-600",
    "text-white",
    "hover:bg-indigo-700",
    "transition",
    "bg-red-600",
    "hover:bg-red-700",

    // Modal classes
    "fixed",
    "inset-0",
    "bg-black",
    "bg-opacity-50",
    "items-center",
    "justify-center",
    "hidden",
    "text-2xl",
    "text-slate-400",
    "text-3xl",
    "px-3",
    "py-2",
    "border",
    "rounded-lg",
    "mb-4",
    "w-full",
    "max-w-md",
    "close-modal",

    // Utility classes
    "hidden",
    "block",
    "flex",
    "gap-2",
    "transition",
    "shadow-lg",
    "container",
    "cardlist",
    "createCard",
    "changeCard",
    "deleteCard",
  ],
  plugins: [],
};
